


class Definitions():
    PUBSUB_ADDRESS= '127.0.0.1'
    PUBSUB_PORT= 1883
    PUBSUB_KEEPALIVE= 60
    TOPIC_CONFIG= 'CONFIG'
    TOPIC_REGISTRATION='REGISTRATION'
    TOPIC_DEVICELIST= 'DEVICELIST'
    TRANSFER_ENCODING= 'UTF-8',
    RECEIVER_TIMEOUT_MS= 100000,
    SERVICENAME_CONFIG= 'configurationservice'
    SERVICENAME_DEVICE= 'deviceservice'
    SERVICENAME_MESSAGEPANEL= 'messagepanelservice'
    PATH_DEVICES='/dev/bus/usb'
    PATH_CONFIG='./config.json'
    USB_LANGID=256
    USB_DEVICE_CLASS_COMMS=2
    USB_INTERFACE_CLASS_COMMS=2
    USB_INTERFACE_SUBCLASS_MODEM=2
    USB_INTERFACE_PROTOCOL_AT=1
    

        


        

